version: 2
jobs:
  build:
    docker:
      - image: circleci/node:6
    branches:
        only:
          - master
    working_directory: ~/workspace
    steps:
      - checkout

      - run:
          name: Install firebase-tools
          command: sudo npm install -g firebase-tools

      - run: 
          name: Decode key file
          command: echo $FIREBASE_KEY | base64 -d > ${HOME}/account-auth.json

      - run:
          name: Setup local environment
          command: echo "export GOOGLE_APPLICATION_CREDENTIALS=${HOME}/account-auth.json" >> $BASH_ENV

      - run:
          name: Deploy Firebase Hosting
          command: |
              firebase deploy --only hosting --project $FIREBASE_PROJECT_ID --token $FIREBASE_TOKEN

      - run:
          name: Deploy Cloud Functions for Firebase
          command: |
              cd functions
              npm install
              npm run build
              firebase deploy --only functions --project $FIREBASE_PROJECT_ID --token $FIREBASE_TOKEN
